CREATE TABLE IF NOT EXISTS payments (
                                      payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      order_id BIGINT NOT NULL,
                                      customer_id BIGINT NOT NULL,
                                      executor_id BIGINT NOT NULL,
                                      payment_sum DECIMAL NOT NULL,
                                      payment_status VARCHAR(20) NOT NULL,
                                      payment_date TIMESTAMP WITHOUT TIME ZONE,
                                      CONSTRAINT pk_payment PRIMARY KEY (payment_id)
);

CREATE TABLE IF NOT EXISTS accounts (
                                       account_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                       user_id BIGINT NOT NULL,
                                       amount DECIMAL NOT NULL,
                                       CONSTRAINT pk_account PRIMARY KEY (account_id)
);