version: '3.8'
services:
  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile.app
    image: discovery-server-image
    container_name: discovery-server
    ports:
      - "8761:8761"

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile.app
    image: gateway-image
    container_name: gateway
    ports:
      - "8080:8080"

  orders-service:
    build:
      context: ./orders
      dockerfile: Dockerfile.app
    image: orders-image
    container_name: order-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://orders-db:5432/orders-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - orders-db

  orders-db:
    image: postgres:14-alpine
    container_name: orders-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=orders-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  users-service:
    build:
      context: ./users
      dockerfile: Dockerfile.app
    image: users-image
    container_name: user-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://users-db:5432/users-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - users-db

  users-db:
    image: postgres:14-alpine
    container_name: users-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=users-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  payments-service:
    build:
      context: ./payments
      dockerfile: Dockerfile.app
    image: payments-image
    container_name: payment-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payments-db:5432/payments-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - payments-db

  payments-db:
    image: postgres:14-alpine
    container_name: payments-db
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=payments-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - "kafka"