CREATE TABLE IF NOT EXISTS orders (
                                      order_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                                      order_name VARCHAR(255),
                                      order_description VARCHAR(250),
                                      customer_id BIGINT NOT NULL,
                                      executor_id BIGINT,
                                      payment_id BIGINT,
                                      order_status VARCHAR(50) NOT NULL,
                                      order_date TIMESTAMP WITHOUT TIME ZONE,
                                      CONSTRAINT pk_order PRIMARY KEY (order_id)
);