package com.aston.mapper;

import com.aston.dto.NewOrderDto;
import com.aston.dto.OrderDto;
import com.aston.model.Order;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper
public interface OrderMapper {
    OrderMapper INSTANCE = Mappers.getMapper(OrderMapper.class);

    @Mapping(target = "executor", ignore = true)
    @Mapping(target = "customer", ignore = true)
    @Mapping(target = "payment", ignore = true)
    OrderDto orderToOrderDto(Order order);

    @Mapping(target = "id", ignore = true) // Ignore id as it's generated by the database
    @Mapping(target = "customerId", ignore = true) // Ignore customer_id, as it's not provided in the DTO
    @Mapping(target = "executorId", ignore = true) // Ignore executor_id, as it's not provided in the DTO
    @Mapping(target = "paymentId", ignore = true) // Ignore payment_id, as it's not provided in the DTO
    @Mapping(target = "status", constant = "NEW") // Set default status to NEW
    @Mapping(target = "date", expression = "java(java.time.LocalDateTime.now())") // Set current date
    @Mapping(target = "name", source = "name")
    @Mapping(target = "description", source = "description")
    Order newOrderDtoToOrder(NewOrderDto newOrderDto);
}
